### ISSUE TITLE
Handle %rsp correctly

### ISSUE THREAD

**Issue by tatetian** [occlum/llvm#3]
%rsp should be bound-checked before being modified directly (e.g., via mov) so that we can maintain an invariance that %rsp is always in the data domain and never have to bound check for frequent operations like push/pop and writes to %rsp-relative addresses (for local variables).

**Comment by Yourens** [comment]
Fixed at commit https://github.com/occlum/llvm/commit/80e5f5c959fc7ae957cbf64ac4eb99d9da02a2b5
